version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ..:/workspaces/pubsub-sample
    working_dir: /workspaces/pubsub-sample
    tty: true
    depends_on:
      - pubsub
    environment:
      PUBSUB_PROJECT_ID: $PUBSUB_PROJECT_ID
      PUBSUB_TOPIC_ID: $PUBSUB_TOPIC_ID
      PUBSUB_DEAD_LETTER_TOPIC_ID: $PUBSUB_DEAD_LETTER_TOPIC_ID
      PUBSUB_SUBSCRIPTION_ID: $PUBSUB_SUBSCRIPTION_ID
      PUBSUB_DEAD_LETTER_SUBSCRIPTION_ID: $PUBSUB_DEAD_LETTER_SUBSCRIPTION_ID
      PUBSUB_EMULATOR_HOST: docker.host.internal:8085
  pubsub:
    image: docker.io/google/cloud-sdk:494.0.0
    ports:
      - 8085:8085
    environment:
      PUBSUB_PROJECT_ID: $PUBSUB_PROJECT_ID
      PUBSUB_TOPIC_ID: $PUBSUB_TOPIC_ID
      PUBSUB_DEAD_LETTER_TOPIC_ID: $PUBSUB_DEAD_LETTER_TOPIC_ID
      PUBSUB_SUBSCRIPTION_ID: $PUBSUB_SUBSCRIPTION_ID
      PUBSUB_DEAD_LETTER_SUBSCRIPTION_ID: $PUBSUB_DEAD_LETTER_SUBSCRIPTION_ID
      PUBSUB_EMULATOR_HOST: 0.0.0.0:8085
    volumes:
      - ../pubsub:/pubsub
    command: /bin/bash /pubsub/command.sh
